spring:
  application:
    name: seller-rating-app
  datasource:
    url: jdbc:postgresql://localhost:5432/SellerRateApp
    username: rating_service
    password: 123454321
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    defer-datasource-initialization: true
  security:
    user:
      name: Pupa
      password: Lupa
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG