spring:
  application:
    name: seller-rating-app
  datasource:
    url: jdbc:postgresql://localhost:5432/SellerRateApp
    username: rating_service
    password: 123454321
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: sellerratingapp
    password: hqnf rhta gpdx yadk
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG