spring.application.name=seller-rating-app

spring.datasource.url=jdbc:postgresql://localhost:5432/SellerRateApp
spring.datasource.username=rating_service
spring.datasource.password=123454321
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
